// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentStats } from "./AgentStats";
import type { PrStats } from "./PrStats";
import type { StatsMetric } from "./StatsMetric";
import type { SystemLoad } from "./SystemLoad";

export type DashboardStats = { activeProjects: StatsMetric, agentsOnline: AgentStats, systemLoad: SystemLoad, pendingPRs: PrStats, };
