// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DashboardAgentLog = { id: string, timestamp: string, agentName: string, agentColor: string, message: string, highlight: string | null, };
