// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserAvatar } from "./UserAvatar";

export type DashboardHumanTask = { id: string, projectId: string, projectName: string, type: string, title: string, description: string, createdAt: string, assignee: UserAvatar | null, };
