// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentAvatar } from "./AgentAvatar";

export type DashboardProject = { id: string, name: string, subtitle: string, status: string, progress: bigint, agents: Array<AgentAvatar>, };
