// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DashboardAgentLog } from "./DashboardAgentLog";
import type { DashboardHumanTask } from "./DashboardHumanTask";
import type { DashboardProject } from "./DashboardProject";
import type { DashboardStats } from "./DashboardStats";

export type DashboardData = { stats: DashboardStats, projects: Array<DashboardProject>, agentLogs: Array<DashboardAgentLog>, humanTasks: Array<DashboardHumanTask>, };
