// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommandExitStatus = { "type": "exit_code", code: number, } | { "type": "success", success: boolean, };
