// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandExitStatus } from "./CommandExitStatus";

/**
 * Command run result
 */
export type CommandRunResult = { exit_status: CommandExitStatus | null, output: string | null, };
