// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Error types for ErrorMessage entries
 */
export type NormalizedEntryError = "tool_error" | "api_error" | "system_error" | "unknown";
