// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TodoStatus } from "./TodoStatus";

/**
 * Todo item for TodoManagement action
 */
export type TodoItem = { content: string, status: TodoStatus, active_form: string, };
