// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tool result wrapper
 */
export type ToolResult = { success: boolean, output: string | null, };
