// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to add a review comment
 */
export type AddReviewCommentRequest = { 
/**
 * Relative path to file (optional - NULL for general comment)
 */
file_path: string | null, 
/**
 * Line number in file (optional - NULL for file-level comment)
 */
line_number: number | null, 
/**
 * Comment text content
 */
content: string, };
