// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Artifact list response
 */
export type ArtifactResponse = { id: string, artifact_key: string, artifact_type: string, size_bytes: bigint | null, file_count: number | null, download_url: string | null, created_at: string, };
