// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response when a build is started (non-blocking)
 */
export type BuildStartedResponse = { attempt_id: string, status: string, };
