// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of a build operation
 */
export type BuildResult = { artifact_key: string, size_bytes: bigint, files_count: number, build_duration_secs: number, };
