// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Build configuration for a project type
 */
export type BuildConfig = { command: string, output_dir: string, };
