// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Build artifact stored in MinIO after a successful build
 */
export type BuildArtifact = { id: string, attempt_id: string, project_id: string, 
/**
 * Storage key in MinIO: builds/{project_id}/{attempt_id}/{artifact_name}
 */
artifact_key: string, 
/**
 * Type of artifact: dist, binary, apk, ipa, image, etc.
 */
artifact_type: string, size_bytes: bigint | null, file_count: number | null, build_command: string | null, build_duration_secs: number | null, created_at: string, };
