// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SprintCarryOverMode } from "./SprintCarryOverMode";

export type CloseSprintResult = { closedSprintId: string, movedTaskCount: bigint, movedToSprintId: string | null, carryOverMode: SprintCarryOverMode, };
