// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateNextSprintRequest } from "./CreateNextSprintRequest";
import type { SprintCarryOverMode } from "./SprintCarryOverMode";

export type CloseSprintRequest = { carry_over_mode: SprintCarryOverMode, next_sprint_id: string | null, create_next_sprint: CreateNextSprintRequest | null, reason: string | null, };
