// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TunnelStatus } from "./TunnelStatus";

export type CloudflareTunnel = { id: string, attempt_id: string, tunnel_id: string, tunnel_name: string, preview_url: string, status: TunnelStatus, created_at: string, expires_at: string | null, deleted_at: string | null, dns_record_id: string | null, docker_project_name: string | null, compose_file_path: string | null, worktree_path: string | null, last_error: string | null, started_at: string | null, stopped_at: string | null, };
