// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeploymentArtifactStrategy } from "./DeploymentArtifactStrategy";
import type { DeploymentEnvironmentSecretInput } from "./DeploymentEnvironmentSecretInput";
import type { DeploymentRuntimeType } from "./DeploymentRuntimeType";
import type { DeploymentTargetType } from "./DeploymentTargetType";
import type { JsonValue } from "./serde_json/JsonValue";

export type CreateDeploymentEnvironmentRequest = { name: string, description: string | null, target_type: DeploymentTargetType, is_enabled: boolean | null, is_default: boolean | null, runtime_type: DeploymentRuntimeType | null, deploy_path: string, artifact_strategy: DeploymentArtifactStrategy | null, branch_policy: JsonValue | null, healthcheck_url: string | null, healthcheck_timeout_secs: number | null, healthcheck_expected_status: number | null, target_config: JsonValue | null, domain_config: JsonValue | null, secrets: Array<DeploymentEnvironmentSecretInput> | null, };
