// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";
import type { TaskType } from "./TaskType";

export type CreateTaskRequest = { project_id: string, requirement_id: string | null, sprint_id: string | null, title: string, description: string | null, task_type: TaskType, assigned_to: string | null, metadata: JsonValue | null, parent_task_id: string | null, };
