// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateSprintRequest = { project_id: string, sequence: number | null, name: string, description: string | null, goal: string | null, start_date: string | null, end_date: string | null, };
