// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to create a project from a template
 */
export type CreateProjectFromTemplateRequest = { template_id: string, name: string, description: string | null, 
/**
 * Override visibility (defaults to private)
 */
visibility: string | null, };
