// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";
import type { ProjectStackSelection } from "./ProjectStackSelection";
import type { ProjectType } from "./ProjectType";

export type CreateProjectRequest = { name: string, description: string | null, repository_url: string | null, metadata: JsonValue | null, 
/**
 * If true, agent changes require human review before commit/push
 */
require_review: boolean | null, create_from_scratch: boolean | null, visibility: string | null, 
/**
 * Preferred tech stack/framework for initialization (e.g., "tauri", "nextjs").
 */
tech_stack: string | null, 
/**
 * Optional layered stack selections (e.g., frontend/backend/database) for richer init prompts.
 */
stack_selections: Array<ProjectStackSelection> | null, 
/**
 * If true (default), create and run the init task automatically.
 */
auto_create_init_task: boolean | null, 
/**
 * Project type classification (defaults to Web if not specified)
 */
project_type: ProjectType | null, 
/**
 * Template ID to create project from (optional)
 */
template_id: string | null, };
