// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateNextSprintRequest = { name: string | null, start_date: string | null, end_date: string | null, goal: string | null, };
