// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";
import type { RequirementPriority } from "./RequirementPriority";

export type CreateRequirementRequest = { project_id: string, sprint_id: string | null, title: string, content: string, priority: RequirementPriority | null, due_date: string | null, metadata: JsonValue | null, };
