// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeploymentSecretType } from "./DeploymentSecretType";

export type DeploymentEnvironmentSecretInput = { secret_type: DeploymentSecretType, value: string, };
