// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeploymentTimelineEventType } from "./DeploymentTimelineEventType";
import type { DeploymentTimelineStep } from "./DeploymentTimelineStep";
import type { JsonValue } from "./serde_json/JsonValue";

export type DeploymentTimelineEvent = { id: string, run_id: string, step: DeploymentTimelineStep, event_type: DeploymentTimelineEventType, message: string, payload: JsonValue, created_at: string, };
