// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeploymentArtifactStrategy } from "./DeploymentArtifactStrategy";
import type { DeploymentRuntimeType } from "./DeploymentRuntimeType";
import type { DeploymentTargetType } from "./DeploymentTargetType";
import type { JsonValue } from "./serde_json/JsonValue";

export type DeploymentEnvironment = { id: string, project_id: string, name: string, slug: string, description: string | null, target_type: DeploymentTargetType, is_enabled: boolean, is_default: boolean, runtime_type: DeploymentRuntimeType, deploy_path: string, artifact_strategy: DeploymentArtifactStrategy, branch_policy: JsonValue, healthcheck_url: string | null, healthcheck_timeout_secs: number, healthcheck_expected_status: number, target_config: JsonValue, domain_config: JsonValue, created_by: string | null, created_at: string, updated_at: string, };
