// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeploymentSecretType } from "./DeploymentSecretType";

export type DeploymentEnvironmentSecret = { id: string, environment_id: string, secret_type: DeploymentSecretType, ciphertext: string, created_at: string, updated_at: string, };
