// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeploymentRunStatus } from "./DeploymentRunStatus";
import type { DeploymentSourceType } from "./DeploymentSourceType";
import type { DeploymentTriggerType } from "./DeploymentTriggerType";
import type { JsonValue } from "./serde_json/JsonValue";

export type DeploymentRun = { id: string, project_id: string, environment_id: string, status: DeploymentRunStatus, trigger_type: DeploymentTriggerType, triggered_by: string | null, source_type: DeploymentSourceType, source_ref: string | null, attempt_id: string | null, started_at: string | null, completed_at: string | null, error_message: string | null, metadata: JsonValue, created_at: string, updated_at: string, };
