// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeploymentReleaseStatus } from "./DeploymentReleaseStatus";
import type { JsonValue } from "./serde_json/JsonValue";

export type DeploymentRelease = { id: string, project_id: string, environment_id: string, run_id: string, version_label: string, artifact_ref: string | null, git_commit_sha: string | null, status: DeploymentReleaseStatus, deployed_at: string, metadata: JsonValue, created_at: string, updated_at: string, };
