// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeploymentTimelineStep = "precheck" | "connect" | "prepare" | "deploy" | "domain_config" | "healthcheck" | "finalize" | "rollback";
