// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeploymentCheckResult } from "./DeploymentCheckResult";

export type DeploymentConnectionTestResponse = { success: boolean, checks: Array<DeploymentCheckResult>, };
