// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for deployment operations
 */
export type DeploymentResponse = { deployment_id: string, url: string, status: string, deployment_type: string, };
