// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeploymentRunStatus = "queued" | "running" | "success" | "failed" | "cancelled" | "rolling_back" | "rolled_back";
