// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeploymentSecretType = "ssh_private_key" | "ssh_password" | "api_token" | "known_hosts" | "env_file";
