// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExecutionProcess = { id: string, attempt_id: string, process_id: number | null, worktree_path: string | null, branch_name: string | null, created_at: string, };
