// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stored file diff for an attempt
 */
export type FileDiff = { id: string, attempt_id: string, file_path: string, old_path: string | null, change_type: string, additions: number, deletions: number, old_content: string | null, new_content: string | null, created_at: string, };
