// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GenerateSprintsRequest = { project_id: string, start_date: string, duration_weeks: number, count: number, };
