// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitLabConfiguration = { id: string, project_id: string, gitlab_project_id: bigint, base_url: string, pat_encrypted: string, webhook_secret: string, created_at: string, updated_at: string, };
