// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitLabWebhook = { id: string, project_id: string, gitlab_id: bigint, url: string, events: Array<string>, secret_token: string, created_at: string, updated_at: string, };
