// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InitSource } from "./InitSource";

/**
 * Metadata for init tasks
 */
export type InitTaskMetadata = { source: InitSource, repository_url: string | null, visibility: string | null, };
