// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Source of project initialization
 */
export type InitSource = "gitlab_import" | "from_scratch";
