// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LinkGitLabProjectRequest = { 
/**
 * GitLab project ID (numeric). Optional if repository_url is provided.
 */
gitlab_project_id: bigint | null, 
/**
 * Repository URL (e.g. https://gitlab.com/group/repo). Resolved to project_id via GitLab API.
 */
repository_url: string | null, };
