// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * List deployments query parameters
 */
export type ListDeploymentsQuery = { 
/**
 * Filter by deployment type
 */
deployment_type: string | null, 
/**
 * Filter by status
 */
status: string | null, 
/**
 * Limit results
 */
limit: number | null, };
