// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeploymentReleaseStatus } from "./DeploymentReleaseStatus";

export type ListDeploymentReleasesQuery = { status: DeploymentReleaseStatus | null, limit: number | null, };
