// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeploymentRunStatus } from "./DeploymentRunStatus";

export type ListDeploymentRunsQuery = { environment_id: string | null, status: DeploymentRunStatus | null, limit: number | null, };
