// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectType } from "./ProjectType";

/**
 * Query parameters for listing templates
 */
export type ListTemplatesQuery = { 
/**
 * Filter by project type
 */
project_type: ProjectType | null, 
/**
 * Filter by official templates only
 */
official_only: boolean | null, };
