// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MergeRequestDb = { id: string, task_id: string, attempt_id: string | null, 
/**
 * GitLab MR IID. NULL for GitHub PRs.
 */
gitlab_mr_iid: bigint | null, web_url: string, status: string, created_at: string, updated_at: string, 
/**
 * Provider: "gitlab" | "github". Default "gitlab".
 */
provider: string, 
/**
 * GitHub PR number. NULL for GitLab MRs.
 */
github_pr_number: bigint | null, };
