// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Normalized log entry extracted from agent output
 */
export type NormalizedLogEntry = { id: string, attempt_id: string, raw_log_id: string | null, entry_type: string, entry_data: JsonValue, line_number: number, created_at: string, };
