// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TunnelStatus } from "./TunnelStatus";

export type PreviewInfo = { id: string, attempt_id: string, preview_url: string, status: TunnelStatus, created_at: string, expires_at: string | null, };
