// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Preview deployment using Cloudflare tunnels
 */
export type PreviewDeployment = { id: string, attempt_id: string, project_id: string, artifact_id: string | null, url: string, tunnel_id: string | null, dns_record_id: string | null, 
/**
 * Deployment status: active, expired, destroyed
 */
status: string, expires_at: string, destroyed_at: string | null, created_at: string, updated_at: string, };
