// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Preview deployment response with extended info
 */
export type PreviewDeploymentResponse = { id: string, attempt_id: string, url: string, status: string, expires_at: string, created_at: string, };
