// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Production deployment to Cloudflare Pages, Workers, or external services
 */
export type ProductionDeployment = { id: string, project_id: string, artifact_id: string | null, 
/**
 * Target platform: pages, workers, container, manual
 */
deployment_type: string, url: string, deployment_id: string | null, 
/**
 * Deployment status: active, failed, superseded
 */
status: string, triggered_by: string | null, metadata: JsonValue, created_at: string, updated_at: string, };
