// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";
import type { ProjectType } from "./ProjectType";

/**
 * Project template for quick scaffolding with predefined tech stacks and settings
 */
export type ProjectTemplate = { id: string, name: string, description: string | null, project_type: ProjectType, repository_url: string, 
/**
 * Array of technologies used in this template, e.g., ["React", "TypeScript", "Vite"]
 */
tech_stack: JsonValue, 
/**
 * Default project settings to apply when creating from this template
 */
default_settings: JsonValue, 
/**
 * Whether this is an officially maintained template
 */
is_official: boolean, created_by: string | null, created_at: string, updated_at: string, };
