// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";
import type { ProjectSettings } from "./ProjectSettings";
import type { ProjectType } from "./ProjectType";

export type Project = { id: string, name: string, description: string | null, repository_url: string | null, metadata: JsonValue, 
/**
 * Legacy field for backward compatibility - use settings.require_review instead
 */
require_review: boolean, architecture_config: JsonValue, 
/**
 * Project-level settings (JSONB) - new unified settings object
 */
settings: ProjectSettings, 
/**
 * Agent settings (router, filters, etc.) - Phase 2
 */
agent_settings: JsonValue, 
/**
 * Project type classification (web, mobile, desktop, extension, api, microservice)
 */
project_type: ProjectType, created_by: string, created_at: string, updated_at: string, };
