// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectAssistantSession = { id: string, project_id: string, user_id: string, status: string, s3_log_key: string | null, created_at: string, ended_at: string | null, };
