// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectRole } from "./ProjectRole";

export type ProjectMember = { id: string, project_id: string, user_id: string, roles: Array<ProjectRole>, created_at: string, updated_at: string, };
