// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Project-level settings controlling agent execution, deployment, review, and notifications.
 * Stored as JSONB in the database for flexibility with schema validation at application layer.
 */
export type ProjectSettings = { 
/**
 * If true, agent changes require human review before commit/push
 */
require_review: boolean, 
/**
 * If true, deploy preview (Cloudflare tunnel) when task completes. Not related to production.
 */
auto_deploy: boolean, 
/**
 * If true, create preview environments for task attempts (legacy alias for auto_deploy)
 */
preview_enabled: boolean, 
/**
 * If true, deploy to production when MR is merged into deploy_branch
 */
production_deploy_on_merge: boolean, 
/**
 * If true, use GitOps workflow (create MRs) vs direct push
 */
gitops_enabled: boolean, 
/**
 * Maximum number of retry attempts for failed tasks
 */
max_retries: number, 
/**
 * Agent execution timeout in minutes
 */
timeout_mins: number, 
/**
 * Preview environment lifetime in days
 */
preview_ttl_days: number, 
/**
 * If true, automatically merge approved MRs
 */
auto_merge: boolean, 
/**
 * Branch that triggers production deployment
 */
deploy_branch: string, 
/**
 * Target branch for merge requests (default: deploy_branch or "main")
 */
mr_target_branch: string | null, 
/**
 * If true, send notification on task success
 */
notify_on_success: boolean, 
/**
 * If true, send notification on task failure
 */
notify_on_failure: boolean, 
/**
 * If true, send notification when review is needed
 */
notify_on_review: boolean, 
/**
 * Notification channels (Slack, email, etc.)
 */
notify_channels: Array<string>, 
/**
 * If true, automatically start task execution on creation
 */
auto_execute: boolean, 
/**
 * Task types to auto-execute: ["bug", "hotfix", "feature", "refactor", "docs", "test", "chore", "spike", "small_task"]
 */
auto_execute_types: Array<string>, 
/**
 * If true, automatically retry failed tasks
 */
auto_retry: boolean, 
/**
 * Queue priority for auto-execute: "low", "normal", "high"
 */
auto_execute_priority: string, 
/**
 * Retry backoff strategy: "fixed", "exponential"
 */
retry_backoff: string, 
/**
 * Maximum concurrent tasks per project
 */
max_concurrent: number, };
