// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectStackLayer } from "./ProjectStackLayer";

export type ProjectStackSelection = { layer: ProjectStackLayer, stack: string, };
