// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectSettings } from "./ProjectSettings";

/**
 * Response for project settings with defaults included for UI reset functionality
 */
export type ProjectSettingsResponse = { settings: ProjectSettings, defaults: ProjectSettings, };
