// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Project-specific role for per-project permissions
 */
export type ProjectRole = "owner" | "admin" | "product_owner" | "developer" | "business_analyst" | "quality_assurance" | "viewer";
