// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to request changes on an attempt
 */
export type RequestChangesRequest = { 
/**
 * Feedback/summary for the agent explaining what needs to change
 */
feedback: string, 
/**
 * Whether to include existing review comments as context (default: true)
 */
include_comments: boolean, };
