// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response containing the new attempt created from request-changes
 */
export type RequestChangesResponse = { 
/**
 * The original attempt that was reviewed
 */
original_attempt_id: string, 
/**
 * The new attempt created with feedback
 */
new_attempt_id: string, 
/**
 * Feedback that was included
 */
feedback: string, 
/**
 * Number of review comments included
 */
comments_included: number, };
