// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";
import type { RequirementPriority } from "./RequirementPriority";
import type { RequirementStatus } from "./RequirementStatus";

export type Requirement = { id: string, project_id: string, sprint_id: string | null, title: string, content: string, status: RequirementStatus, priority: RequirementPriority, due_date: string | null, metadata: JsonValue, created_by: string, created_at: string, updated_at: string, };
