// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Review comment on a task attempt
 * Supports line-level, file-level, and general comments for code review workflow
 */
export type ReviewComment = { id: string, attempt_id: string, user_id: string, 
/**
 * Relative path to file in repository. NULL for general comments
 */
file_path: string | null, 
/**
 * Line number in file. NULL for file-level or general comments
 */
line_number: number | null, 
/**
 * Comment text content
 */
content: string, 
/**
 * Whether this comment has been addressed/resolved
 */
resolved: boolean, 
/**
 * User who marked the comment as resolved
 */
resolved_by: string | null, 
/**
 * Timestamp when comment was resolved
 */
resolved_at: string | null, created_at: string, updated_at: string, };
