// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SprintTaskMovement = { id: string, projectId: string, taskId: string, fromSprintId: string | null, toSprintId: string | null, movedBy: string | null, movedAt: string, reason: string | null, };
