// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SprintOverview = { sprintId: string, projectId: string, totalTasks: bigint, doneTasks: bigint, canceledTasks: bigint, remainingTasks: bigint, completionRate: number, movedInCount: bigint, movedOutCount: bigint, };
