// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SprintStatus } from "./SprintStatus";

export type Sprint = { id: string, project_id: string, sequence: number, name: string, description: string | null, goal: string | null, status: SprintStatus, start_date: string | null, end_date: string | null, closed_at: string | null, closed_by: string | null, created_at: string, updated_at: string, };
