// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeploymentSourceType } from "./DeploymentSourceType";
import type { JsonValue } from "./serde_json/JsonValue";

export type StartDeploymentRunRequest = { source_type: DeploymentSourceType | null, source_ref: string | null, attempt_id: string | null, metadata: JsonValue | null, };
