// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Subagent relationship tracking when agents spawn subagents via Task tool
 */
export type SubagentRelationship = { id: string, parent_attempt_id: string, child_attempt_id: string, spawned_at: string, spawn_tool_use_id: string | null, };
