// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * System-wide role for global permissions
 */
export type SystemRole = "admin" | "product_owner" | "business_analyst" | "developer" | "quality_assurance" | "viewer";
