// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SystemSettingsResponse = { gitlab_url: string, gitlab_pat_configured: boolean, gitlab_auto_sync: boolean, agent_cli_provider: string, cloudflare_account_id: string | null, cloudflare_api_token_configured: boolean, cloudflare_zone_id: string | null, cloudflare_base_domain: string | null, notifications_email_enabled: boolean, notifications_slack_enabled: boolean, notifications_slack_webhook_url: string | null, 
/**
 * Path where agent worktrees (cloned source code) are stored. From env WORKTREES_PATH.
 */
worktrees_path: string, preferred_agent_language: string, updated_at: string, };
