// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SystemSettings = { id: string, gitlab_url: string, gitlab_pat_encrypted: string | null, gitlab_auto_sync: boolean, agent_cli_provider: string, cloudflare_account_id: string | null, cloudflare_api_token_encrypted: string | null, cloudflare_zone_id: string | null, cloudflare_base_domain: string | null, notifications_email_enabled: boolean, notifications_slack_enabled: boolean, notifications_slack_webhook_url: string | null, created_at: string, updated_at: string, };
