// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttemptStatus } from "./AttemptStatus";
import type { JsonValue } from "./serde_json/JsonValue";

export type TaskAttempt = { id: string, task_id: string, status: AttemptStatus, started_at: string | null, completed_at: string | null, error_message: string | null, metadata: JsonValue, created_at: string, diff_total_files: number | null, diff_total_additions: number | null, diff_total_deletions: number | null, diff_saved_at: string | null, s3_diff_key: string | null, s3_diff_size: bigint | null, s3_diff_saved_at: string | null, s3_log_key: string | null, };
