// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";
import type { TaskStatus } from "./TaskStatus";
import type { TaskType } from "./TaskType";

export type Task = { id: string, project_id: string, requirement_id: string | null, sprint_id: string | null, title: string, description: string | null, task_type: TaskType, status: TaskStatus, assigned_to: string | null, parent_task_id: string | null, gitlab_issue_id: number | null, metadata: JsonValue, created_by: string, created_at: string, updated_at: string, };
