// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to trigger a production deployment
 */
export type TriggerDeployRequest = { 
/**
 * The artifact ID to deploy (if not provided, will use latest build)
 */
artifact_id: string | null, 
/**
 * Target deployment type: pages, workers, container
 */
deployment_type: string | null, };
