// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to trigger a build for an attempt
 */
export type TriggerBuildRequest = { 
/**
 * Override build command (optional)
 */
build_command: string | null, 
/**
 * Override output directory (optional)
 */
output_dir: string | null, };
