// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskStatus } from "./TaskStatus";

export type UpdateTaskRequest = { title: string | null, description: string | null, status: TaskStatus | null, assigned_to: string | null, sprint_id: string | null, };
