// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";
import type { ProjectType } from "./ProjectType";

export type UpdateProjectTemplateRequest = { name: string | null, description: string | null, project_type: ProjectType | null, repository_url: string | null, tech_stack: Array<string> | null, default_settings: JsonValue | null, is_official: boolean | null, };
