// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SprintStatus } from "./SprintStatus";

export type UpdateSprintRequest = { name: string | null, description: string | null, goal: string | null, status: SprintStatus | null, start_date: string | null, end_date: string | null, };
