// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to update project settings (partial update supported)
 */
export type UpdateProjectSettingsRequest = { require_review: boolean | null, auto_deploy: boolean | null, preview_enabled: boolean | null, gitops_enabled: boolean | null, max_retries: number | null, timeout_mins: number | null, preview_ttl_days: number | null, auto_merge: boolean | null, deploy_branch: string | null, mr_target_branch: string | null, notify_on_success: boolean | null, notify_on_failure: boolean | null, notify_on_review: boolean | null, notify_channels: Array<string> | null, auto_execute: boolean | null, auto_execute_types: Array<string> | null, auto_retry: boolean | null, auto_execute_priority: string | null, retry_backoff: string | null, max_concurrent: number | null, };
