// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";
import type { RequirementPriority } from "./RequirementPriority";
import type { RequirementStatus } from "./RequirementStatus";

export type UpdateRequirementRequest = { title: string | null, content: string | null, sprint_id: string | null, status: RequirementStatus | null, priority: RequirementPriority | null, due_date: string | null, metadata: JsonValue | null, };
