// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type UpdateProjectRequest = { name: string | null, description: string | null, repository_url: string | null, metadata: JsonValue | null, require_review: boolean | null, };
