// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SystemRole } from "./SystemRole";

export type User = { id: string, email: string, name: string, avatar_url: string | null, gitlab_id: number | null, gitlab_username: string | null, global_roles: Array<SystemRole>, created_at: string, updated_at: string, };
