// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Workspace repository for multi-repo support (Phase 4)
 */
export type WorkspaceRepo = { id: string, attempt_id: string, project_id: string, repo_name: string, repo_url: string, worktree_path: string, relative_path: string, target_branch: string, base_branch: string, is_primary: boolean, metadata: JsonValue, created_at: string, updated_at: string, };
