// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tool action/invocation extracted from logs
 */
export type ActionType = { tool_name: string, action: string, target: string | null, timestamp: string, line_number: number, };
