// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ActionOperation = { target: string | null, line_number: number, timestamp: string, };
