// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageFilter } from "./MessageFilter";

/**
 * Agent settings for router service and execution behavior
 */
export type AgentSettings = { enable_router_service: boolean, router_version: string, router_filters: Array<MessageFilter>, router_timeout_ms: bigint, };
