// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionOperation } from "./ActionOperation";

/**
 * Aggregated consecutive operations
 */
export type AggregatedAction = { tool_name: string, action: string, operations: Array<ActionOperation>, start_line: number, end_line: number, timestamp_start: string, timestamp_end: string, total_count: number, };
