// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileChangeType } from "./FileChangeType";

/**
 * File change operation (create/modify/delete/rename)
 */
export type FileChange = { path: string, change_type: FileChangeType, lines_added: number | null, lines_removed: number | null, timestamp: string, line_number: number, };
