// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionType } from "./ActionType";
import type { AggregatedAction } from "./AggregatedAction";
import type { FileChange } from "./FileChange";
import type { SubagentSpawn } from "./SubagentSpawn";
import type { TodoItem } from "./TodoItem";
import type { ToolStatus } from "./ToolStatus";

/**
 * Normalized log entry extracted from raw agent logs
 */
export type NormalizedEntry = { "type": "Action" } & ActionType | { "type": "AggregatedAction" } & AggregatedAction | { "type": "SubagentSpawn" } & SubagentSpawn | { "type": "FileChange" } & FileChange | { "type": "TodoItem" } & TodoItem | { "type": "ToolStatus" } & ToolStatus;
