// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Subagent spawn tracking
 */
export type SubagentSpawn = { child_attempt_id: string, task_description: string, tool_use_id: string, timestamp: string, line_number: number, };
