// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TodoStatus } from "./TodoStatus";

/**
 * Todo item extracted from agent output
 */
export type TodoItem = { status: TodoStatus, content: string, timestamp: string, line_number: number, };
