// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutionStatus } from "./ExecutionStatus";

/**
 * Tool execution status (success/failure)
 */
export type ToolStatus = { tool_name: string, status: ExecutionStatus, error_message: string | null, timestamp: string, line_number: number, };
